import { useState, useEffect, useCallback } from "react";

type Language = "th" | "en";

const translations = {
  th: {
    "nav.dashboard": "แดชบอร์ด",
    "nav.sales": "ขาย",
    "nav.production": "วางแผนการผลิต",
    "nav.accounting": "ระบบบัญชี",
    "nav.inventory": "สินค้าและบริการ",
    "nav.customers": "ลูกค้า",
    "nav.master_data": "ข้อมูลหลัก",
    "nav.reports": "รายงาน",
    "nav.users": "จัดการผู้ใช้",
    "nav.logout": "ออกจากระบบ",
    
    "dashboard.title": "แดชบอร์ด",
    "dashboard.revenue": "รายได้",
    "dashboard.growth": "เติบโต",
    "dashboard.expenses": "ค่าใช้จ่าย",
    "dashboard.profit": "กำไรสุทธิ",
    "dashboard.pending_orders": "ออเดอร์รอดำเนินการ",
    "dashboard.active_users": "ผู้ใช้งานระบบ",
    "dashboard.low_stock": "สินค้าใกล้หมด",
    "dashboard.inventory_value": "มูลค่าสินค้าคงคลัง",
    "dashboard.production_schedule": "แผนการผลิต",
    "dashboard.financial_summary": "สรุปทางการเงิน",
    "dashboard.recent_activities": "กิจกรรมล่าสุด",
    "dashboard.view_all": "ดูทั้งหมด",
    
    "production.title": "วางแผนการผลิต",
    "production.status.completed": "เสร็จสิ้น",
    "production.status.in_progress": "กำลังผลิต",
    "production.status.pending": "รอเริ่มผลิต",
    "production.status.delayed": "ล่าช้า",
    "production.order_number": "หมายเลขออเดอร์",
    "production.product": "ผลิตภัณฑ์",
    "production.quantity": "จำนวน",
    "production.status": "สถานะ",
    "production.priority": "ลำดับความสำคัญ",
    "production.start_date": "วันที่เริ่ม",
    "production.end_date": "วันที่สิ้นสุด",
    "production.notes": "หมายเหตุ",
    "production.add_order": "เพิ่มออเดอร์ใหม่",
    
    "accounting.title": "ระบบบัญชี",
    "accounting.type": "ประเภท",
    "accounting.category": "หมวดหมู่",
    "accounting.description": "รายละเอียด",
    "accounting.amount": "จำนวนเงิน",
    "accounting.date": "วันที่",
    "accounting.reference": "เลขที่อ้างอิง",
    "accounting.income": "รายได้",
    "accounting.expense": "รายจ่าย",
    "accounting.add_transaction": "เพิ่มรายการใหม่",
    
    "inventory.title": "สินค้าคงคลัง",
    "inventory.product": "สินค้า",
    "inventory.sku": "รหัสสินค้า",
    "inventory.category": "หมวดหมู่",
    "inventory.unit": "หน่วย",
    "inventory.quantity": "จำนวน",
    "inventory.min_stock": "สต็อกขั้นต่ำ",
    "inventory.max_stock": "สต็อกสูงสุด",
    "inventory.location": "ที่เก็บ",
    "inventory.status.normal": "ปกติ",
    "inventory.status.low": "ใกล้หมด",
    "inventory.status.out": "หมด",
    
    "reports.title": "รายงาน",
    "reports.financial": "รายงานการเงิน",
    "reports.production": "รายงานการผลิต",
    "reports.inventory": "รายงานสินค้าคงคลัง",
    "reports.sales": "รายงานการขาย",
    
    "sales.title": "ขาย",
    "sales.quotations": "ใบเสนอราคา",
    "sales.new_quotation": "สร้างใบเสนอราคาใหม่",
    "sales.quotation_number": "เลขที่ใบเสนอราคา",
    "sales.customer": "ลูกค้า",
    "sales.date": "วันที่",
    "sales.valid_until": "ใช้ได้ถึงวันที่",
    "sales.items": "รายการสินค้า",
    "sales.product": "สินค้า",
    "sales.quantity": "จำนวน",
    "sales.unit_price": "ราคาต่อหน่วย",
    "sales.total": "รวม",
    "sales.subtotal": "รวมย่อย",
    "sales.discount": "ส่วนลด",
    "sales.tax": "ภาษี",
    "sales.grand_total": "รวมทั้งสิ้น",
    "sales.notes": "หมายเหตุ",
    "sales.terms": "เงื่อนไขการชำระเงิน",
    "sales.status.draft": "ร่าง",
    "sales.status.sent": "ส่งแล้ว",
    "sales.status.accepted": "ยอมรับ",
    "sales.status.rejected": "ปฏิเสธ",
    "sales.status.expired": "หมดอายุ",
    "sales.add_item": "เพิ่มรายการ",
    "sales.remove_item": "ลบรายการ",
    "sales.select_customer": "เลือกลูกค้า",
    "sales.select_product": "เลือกสินค้า",

    "users.title": "จัดการผู้ใช้",
    "users.username": "ชื่อผู้ใช้",
    "users.email": "อีเมล",
    "users.first_name": "ชื่อ",
    "users.last_name": "นามสกุล",
    "users.role": "บทบาท",
    "users.status": "สถานะ",
    "users.active": "ใช้งาน",
    "users.inactive": "ไม่ใช้งาน",
    
    "login.title": "เข้าสู่ระบบ",
    "login.subtitle": "เข้าสู่ระบบเพื่อจัดการการผลิตและบัญชี",
    "login.username": "ชื่อผู้ใช้",
    "login.password": "รหัสผ่าน",
    "login.button": "เข้าสู่ระบบ",
    
    "common.loading": "กำลังโหลด...",
    "common.save": "บันทึก",
    "common.cancel": "ยกเลิก",
    "common.edit": "แก้ไข",
    "common.delete": "ลบ",
    "common.add": "เพิ่ม",
    "common.search": "ค้นหา",
    "common.status": "สถานะ",
    "common.date": "วันที่",
    "common.amount": "จำนวน",
    "common.description": "รายละเอียด",
    "common.actions": "การดำเนินการ",
    "common.view": "ดู",
    "common.update": "อัปเดต",
  },
  en: {
    "nav.dashboard": "Dashboard",
    "nav.sales": "Sales",
    "nav.production": "Production Planning",
    "nav.accounting": "Accounting",
    "nav.inventory": "Inventory",
    "nav.customers": "Customers",
    "nav.master_data": "Master Data",
    "nav.reports": "Reports",
    "nav.users": "User Management",
    "nav.logout": "Logout",
    
    "dashboard.title": "Dashboard",
    "dashboard.revenue": "Revenue",
    "dashboard.growth": "Growth",
    "dashboard.expenses": "Expenses",
    "dashboard.profit": "Net Profit",
    "dashboard.pending_orders": "Pending Orders",
    "dashboard.active_users": "Active Users",
    "dashboard.low_stock": "Low Stock Items",
    "dashboard.inventory_value": "Inventory Value",
    "dashboard.production_schedule": "Production Schedule",
    "dashboard.financial_summary": "Financial Summary",
    "dashboard.recent_activities": "Recent Activities",
    "dashboard.view_all": "View All",
    
    "production.title": "Production Planning",
    "production.status.completed": "Completed",
    "production.status.in_progress": "In Progress", 
    "production.status.pending": "Pending",
    "production.status.delayed": "Delayed",
    "production.order_number": "Order Number",
    "production.product": "Product",
    "production.quantity": "Quantity",
    "production.status": "Status",
    "production.priority": "Priority",
    "production.start_date": "Start Date",
    "production.end_date": "End Date",
    "production.notes": "Notes",
    "production.add_order": "Add New Order",
    
    "accounting.title": "Accounting",
    "accounting.type": "Type",
    "accounting.category": "Category",
    "accounting.description": "Description",
    "accounting.amount": "Amount",
    "accounting.date": "Date",
    "accounting.reference": "Reference",
    "accounting.income": "Income",
    "accounting.expense": "Expense",
    "accounting.add_transaction": "Add Transaction",
    
    "inventory.title": "Inventory",
    "inventory.product": "Product",
    "inventory.sku": "SKU",
    "inventory.category": "Category",
    "inventory.unit": "Unit",
    "inventory.quantity": "Quantity",
    "inventory.min_stock": "Min Stock",
    "inventory.max_stock": "Max Stock",
    "inventory.location": "Location",
    "inventory.status.normal": "Normal",
    "inventory.status.low": "Low Stock",
    "inventory.status.out": "Out of Stock",
    
    "reports.title": "Reports",
    "reports.financial": "Financial Reports",
    "reports.production": "Production Reports",
    "reports.inventory": "Inventory Reports",
    "reports.sales": "Sales Reports",
    
    "sales.title": "Sales",
    "sales.quotations": "Quotations",
    "sales.new_quotation": "Create New Quotation",
    "sales.quotation_number": "Quotation Number",
    "sales.customer": "Customer",
    "sales.date": "Date",
    "sales.valid_until": "Valid Until",
    "sales.items": "Items",
    "sales.product": "Product",
    "sales.quantity": "Quantity",
    "sales.unit_price": "Unit Price",
    "sales.total": "Total",
    "sales.subtotal": "Subtotal",
    "sales.discount": "Discount",
    "sales.tax": "Tax",
    "sales.grand_total": "Grand Total",
    "sales.notes": "Notes",
    "sales.terms": "Payment Terms",
    "sales.status.draft": "Draft",
    "sales.status.sent": "Sent",
    "sales.status.accepted": "Accepted",
    "sales.status.rejected": "Rejected",
    "sales.status.expired": "Expired",
    "sales.add_item": "Add Item",
    "sales.remove_item": "Remove Item",
    "sales.select_customer": "Select Customer",
    "sales.select_product": "Select Product",
    
    "users.title": "User Management",
    "users.username": "Username",
    "users.email": "Email",
    "users.first_name": "First Name",
    "users.last_name": "Last Name",
    "users.role": "Role",
    "users.status": "Status",
    "users.active": "Active",
    "users.inactive": "Inactive",
    
    "login.title": "Sign In",
    "login.subtitle": "Sign in to manage production and accounting",
    "login.username": "Username",
    "login.password": "Password",
    "login.button": "Sign In",
    
    "common.loading": "Loading...",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.add": "Add",
    "common.search": "Search",
    "common.status": "Status",
    "common.date": "Date",
    "common.amount": "Amount",
    "common.description": "Description",
    "common.actions": "Actions",
    "common.view": "View",
    "common.update": "Update",
  }
};

let currentLanguage: Language = "th";

export function useLanguage() {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    currentLanguage = (saved as Language) || "th";
    return currentLanguage;
  });

  const setLanguage = useCallback((newLanguage: Language) => {
    currentLanguage = newLanguage;
    localStorage.setItem("language", newLanguage);
    setLanguageState(newLanguage);
  }, []);

  const t = useCallback((key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  }, [language]);

  return {
    language,
    setLanguage,
    t
  };
}